env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: { react/react-in-jsx-scope: 0, react/prop-types: 0,  "jsx-a11y/label-has-associated-control": [ 2, {"controlComponents": ["CustomInput"],}] }
ignorePatterns: ['node_modules/*', '**/.*', 'dist/*']
